name: google_maps_app
description: Flutter project with Google Maps API.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_nord_theme: ^2.1.0
  provider: ^6.0.3
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
